package com.fis.me.practice;

import java.io.Serializable;

/**
 * This is a domain class represents a category.
 * @author Shridhar Patil
 *
 */
public class Category implements Serializable{
	/**
	 * This refers to unique category Id.
	 * Here it is simply generated uing the current time ,but in real time application it should be generated by some stratergy and algorithm.
	 */
	private Long categoryId = System.currentTimeMillis();
	/**
	 * Name of expense category.
	 */
	private String name;

	public Category(String name) {
		this.name = name;
	}

	public Category(Long categoryId, String name) {
		this.categoryId = categoryId;
		this.name = name;
	}

	public Category() {
	}

	public Long getCategoryId() {
		return categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
}
