package com.fis.me.practice;

import java.io.Serializable;
import java.util.Date;
/**
 * This is a domain class represents a <code>Expense</code>
 * @author Shridhar Patil
 *
 */

public class Expense implements Serializable {
	/**
	 * This refers to unique expenseId.
	 * Here it is simply generated uing the current time ,but in real time application it should be generated by some stratergy and algorithm.
	 */
	private Long expenseId=System.currentTimeMillis();
	/**
	 * This refers to unique expenseId.
	 * Here it is simply generated uing the current time ,but in real time application it should be generated by some stratergy and algorithm.
	 */
	private Long categoryId;//FK
	/**
	 * This variable is used to Store Float Amount.
	 */
	private Float amount;
	/**
	 * This variable is used to store the Date 
	 */
	private Date date;
	/**
	 * This variable is used to store the Additional details.
	 */
	private String remark;
	
	/**
	 * This no-arg constructor is used to initialize the 
	 */
	public Expense() {
	}
	/**
	 * this is the parameterised Constructor
	 * @param expenseId generated value.
	 * @param categoryId generated value.
	 * @param amount Float Value amount.
	 * @param date takes the date object.
	 * @param remark Additional Details.
	 */
	public Expense(Long expenseId, Long categoryId, Float amount, Date date, String remark) {
		this.expenseId = expenseId;
		this.categoryId = categoryId;
		this.amount = amount;
		this.date = date;
		this.remark = remark;
	}

	/**
	 * This is the Parameterized Constructor.
	 * @param categoryId
	 * @param amount
	 * @param date
	 * @param remark
	 */
	public Expense( Long categoryId, Float amount, Date date, String remark) {
		this.categoryId = categoryId;
		this.amount = amount;
		this.date = date;
		this.remark = remark;
	}


	public Long getExpenseId() {
		return expenseId;
	}
	public void setExpenseId(Long expenseId) {
		this.expenseId = expenseId;
	}
	public Long getCategoryId() {
		return categoryId;
	}
	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}
	public Float getAmount() {
		return amount;
	}
	public void setAmount(Float amount) {
		this.amount = amount;
	}
	public Date getDate() {
		return date;
	}
	public void setDate(Date date) {
		this.date = date;
	}
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	

}
